chore: update husky scripts

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,1 +1,7 @@
-npm t || { echo -e '\n\e[31mTests failed!\e[93m'; exit 1; }
+#!/usr/bin/env bash
+
+if [ -z "${BASH:-}" ]; then
+  exec bash "$0" "$@"
+fi
+
+npm run test || { echo -e '\n\e[31mTests failed!\e[93m'; exit 1; }
